system-ghc: true
resolver: ghc-9.2.7

extra-deps:
- megaparsec-9.3.0
- case-insensitive-1.2.1.0
- parser-combinators-1.3.0
- scientific-0.3.7.0
- hashable-1.4.2.0
- integer-logarithms-1.0.3.1
- primitive-0.8.0.0
- data-array-byte-0.1.0.1
